services:
  weaviate:
    image: semitechnologies/weaviate:1.25.7
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://transformers:8080"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    depends_on:
      transformers:
        condition: service_started

  transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    restart: unless-stopped
    environment:
      ENABLE_CUDA: "0"
    deploy:
      resources:
        limits:
          memory: 4g
